# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

In [1]:
# Import pandas
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\zkus\AppData\Local\Temp\ipykernel_12376\3422465919.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\zkus\AppData\Local\Temp\ipykernel_12376\3422465919.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\zkus\AppData\Local\Temp\ipykernel_12376\3422465919.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\zkus\AppData\Local\Temp\ipykernel_12376\3422465919.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\zkus\AppData\Local\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [2]:
# Create a series of three different colours
colours = pd.Series(["Blue", "Red", "White"])

In [3]:
# View the series of different colours
colours

0     Blue
1      Red
2    White
dtype: object

In [4]:
# Create a series of three different car types and view it
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [5]:
# Combine the Series of cars and colours into a DataFrame
car_data = pd.DataFrame({"Car make": cars,
                         "Colour": colours})
car_data

  Car make Colour
0      BMW   Blue
1   Toyota    Red
2    Honda  White

In [6]:
# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [7]:
# Export the DataFrame you created to a .csv file
car_sales.to_csv("exported-car-sales.csv")

In [8]:
# Find the different datatypes of the car data DataFrame
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [9]:
# Describe your current car sales DataFrame using describe()
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [10]:
# Get information about your DataFrame using info()
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

What does it show you?

In [11]:
# Create a Series of different numbers and find the mean of them
series = pd.Series([999, 22203, 43920])
series.mean()

np.float64(22374.0)

In [12]:
# Create a Series of different numbers and find the sum of them
series = pd.Series([482392, 34994, 22])
series.sum()

np.int64(517408)

In [13]:
# List out all the column names of the car sales DataFrame
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [14]:
# Find the length of the car sales DataFrame
len(car_sales)

10

In [15]:
# Show the first 5 rows of the car sales DataFrame
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [16]:
# Show the first 7 rows of the car sales DataFrame
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [17]:
# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [18]:
# Use .loc to select the row at index 3 of the car sales DataFrame
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [19]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

Notice how they're the same? Why do you think this is? 

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [49]:
# Select the "Odometer (KM)" column from the car sales DataFrame
car_sales["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [50]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame
car_sales["Odometer (KM)"].mean()

np.float64(78601.4)

In [51]:
# Select the rows with over 100,000 kilometers on the Odometer
car_sales[car_sales['Odometer (KM)'] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00

In [52]:
# Create a crosstab of the Make and Doors columns
pd.crosstab(car_sales['Make'], car_sales['Doors'])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [53]:
# Group columns of the car sales DataFrame by the Make column and find the average
car_sales.groupby(['Make']).mean(numeric_only=True)

        Odometer (KM)  Doors
Make
BMW      11179.000000   5.00
Honda    62778.333333   4.00
Nissan  122347.500000   4.00
Toyota   85451.250000   3.75

In [25]:
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline

In [26]:
# Create a histogram of the Odometer column using hist()

In [27]:
# Try to plot the Price column using plot()

Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [60]:
# Remove the punctuation from price column
car_sales['Price'] = car_sales['Price'].astype(str).str.replace(r"[\$\,\.]", "", regex=True)

In [61]:
# Check the changes to the price column
car_sales

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   400000
1   Honda    Red          87899      4   500000
2  Toyota   Blue          32549      3   700000
3     BMW  Black          11179      5  2200000
4  Nissan  White         213095      4   350000
5  Toyota  Green          99213      4   450000
6   Honda   Blue          45698      4   750000
7   Honda   Blue          54738      4   700000
8  Toyota  White          60000      4   625000
9  Nissan  White          31600      4   970000

In [62]:
# Remove the two extra zeros at the end of the price column
car_sales['Price'] = car_sales['Price'].str[:-2]

In [63]:
# Check the changes to the Price column
car_sales['Price']

0     4000
1     5000
2     7000
3    22000
4     3500
5     4500
6     7500
7     7000
8     6250
9     9700
Name: Price, dtype: object

In [65]:
# Change the datatype of the Price column to integers
car_sales['Price'] = car_sales['Price'].astype(int)
car_sales

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [66]:
# Lower the strings of the Make column
car_sales['Make'].str.lower()

0    toyota
1     honda
2    toyota
3       bmw
4    nissan
5    toyota
6     honda
7     honda
8    toyota
9    nissan
Name: Make, dtype: object

If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [67]:
# Make lowering the case of the Make column permanent
car_sales['Make'] = car_sales['Make'].str.lower()

In [68]:
# Check the car sales DataFrame
car_sales

     Make Colour  Odometer (KM)  Doors  Price
0  toyota  White         150043      4   4000
1   honda    Red          87899      4   5000
2  toyota   Blue          32549      3   7000
3     bmw  Black          11179      5  22000
4  nissan  White         213095      4   3500
5  toyota  Green          99213      4   4500
6   honda   Blue          45698      4   7500
7   honda   Blue          54738      4   7000
8  toyota  White          60000      4   6250
9  nissan  White          31600      4   9700

Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [69]:
# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")
car_sales_missing_data = pd.read_csv("car-sales-missing-data.csv")

# Check out the new DataFrame
car_sales_missing_data

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [70]:
# Fill the Odometer column missing values with the mean of the column inplace
car_sales_missing_data['Odometer'].fillna(car_sales_missing_data['Odometer'].mean(), inplace=True)

C:\Users\zkus\AppData\Local\Temp\ipykernel_12376\2108762986.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing_data['Odometer'].fillna(car_sales_missing_data['Odometer'].mean(), inplace=True)

In [71]:
# View the car sales missing DataFrame and verify the changes
car_sales_missing_data

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [72]:
# Remove the rest of the missing data inplace
car_sales_missing_data.dropna(inplace=True)

In [73]:
# Verify the missing values are removed by viewing the DataFrame
car_sales_missing_data

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

We'll now start to add columns to our DataFrame.

In [74]:
# Create a "Seats" column where every row has a value of 5
car_sales_missing_data['Seats'] = 5
car_sales_missing_data

     Make Colour       Odometer  Doors    Price  Seats
0  Toyota  White  150043.000000    4.0   $4,000      5
1   Honda    Red   87899.000000    4.0   $5,000      5
2  Toyota   Blue   92302.666667    3.0   $7,000      5
3     BMW  Black   11179.000000    5.0  $22,000      5
4  Nissan  White  213095.000000    4.0   $3,500      5
5  Toyota  Green   92302.666667    4.0   $4,500      5

In [75]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame
car_sales_missing_data['Engine Size'] = [1.3, 4.3, 2.3, 3.3, 3.0, 4.5]
car_sales_missing_data

     Make Colour       Odometer  Doors    Price  Seats  Engine Size
0  Toyota  White  150043.000000    4.0   $4,000      5          1.3
1   Honda    Red   87899.000000    4.0   $5,000      5          4.3
2  Toyota   Blue   92302.666667    3.0   $7,000      5          2.3
3     BMW  Black   11179.000000    5.0  $22,000      5          3.3
4  Nissan  White  213095.000000    4.0   $3,500      5          3.0
5  Toyota  Green   92302.666667    4.0   $4,500      5          4.5

In [78]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame
car_sales['Car per kilometer'] = car_sales['Price'].astype(int) / car_sales_missing_data['Odometer'].astype(int)
car_sales

     Make Colour  Odometer (KM)  Doors  Price  Car per kilometer
0  toyota  White         150043      4   4000           0.026659
1   honda    Red          87899      4   5000           0.056883
2  toyota   Blue          32549      3   7000           0.075838
3     bmw  Black          11179      5  22000           1.967976
4  nissan  White         213095      4   3500           0.016425
5  toyota  Green          99213      4   4500           0.048753
6   honda   Blue          45698      4   7500                NaN
7   honda   Blue          54738      4   7000                NaN
8  toyota  White          60000      4   6250                NaN
9  nissan  White          31600      4   9700                NaN

In [80]:
# Remove the last column you added using .drop()
car_sales.drop("Car per kilometer", axis=1)

     Make Colour  Odometer (KM)  Doors  Price
0  toyota  White         150043      4   4000
1   honda    Red          87899      4   5000
2  toyota   Blue          32549      3   7000
3     bmw  Black          11179      5  22000
4  nissan  White         213095      4   3500
5  toyota  Green          99213      4   4500
6   honda   Blue          45698      4   7500
7   honda   Blue          54738      4   7000
8  toyota  White          60000      4   6250
9  nissan  White          31600      4   9700

In [82]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable
car_sales_shuffled = car_sales.sample(frac=1)

Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [83]:
# Reset the indexes of the shuffled DataFrame
car_sales_shuffled.reset_index()

   index    Make Colour  Odometer (KM)  Doors  Price  Car per kilometer
0      7   honda   Blue          54738      4   7000                NaN
1      0  toyota  White         150043      4   4000           0.026659
2      5  toyota  Green          99213      4   4500           0.048753
3      2  toyota   Blue          32549      3   7000           0.075838
4      3     bmw  Black          11179      5  22000           1.967976
5      4  nissan  White         213095      4   3500           0.016425
6      9  nissan  White          31600      4   9700                NaN
7      6   honda   Blue          45698      4   7500                NaN
8      8  toyota  White          60000      4   6250                NaN
9      1   honda    Red          87899      4   5000           0.056883

Notice the index numbers have been changed to have order (start from 0).

In [86]:
# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame
car_sales['Odometer (Miles)'] = car_sales['Odometer (KM)'].apply(lambda x: x/1.6)
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Car per kilometer,Odometer (Miles)
0,toyota,White,150043,4,4000,0.026659,93776.875
1,honda,Red,87899,4,5000,0.056883,54936.875
2,toyota,Blue,32549,3,7000,0.075838,20343.125
3,bmw,Black,11179,5,22000,1.967976,6986.875
4,nissan,White,213095,4,3500,0.016425,133184.375
5,toyota,Green,99213,4,4500,0.048753,62008.125
6,honda,Blue,45698,4,7500,NaN,28561.250
7,honda,Blue,54738,4,7000,NaN,34211.250
8,toyota,White,60000,4,6250,NaN,37500.000
9,nissan,White,31600,4,9700,NaN,19750.000

In [88]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers
car_sales.rename(columns={"Odometer (KM)": "Odometer (Miles)"}, inplace=True)
car_sales

,Make,Colour,Odometer (Miles),Doors,Price,Car per kilometer,Odometer (Miles)
0,toyota,White,150043,4,4000,0.026659,93776.875
1,honda,Red,87899,4,5000,0.056883,54936.875
2,toyota,Blue,32549,3,7000,0.075838,20343.125
3,bmw,Black,11179,5,22000,1.967976,6986.875
4,nissan,White,213095,4,3500,0.016425,133184.375
5,toyota,Green,99213,4,4500,0.048753,62008.125
6,honda,Blue,45698,4,7500,NaN,28561.250
7,honda,Blue,54738,4,7000,NaN,34211.250
8,toyota,White,60000,4,6250,NaN,37500.000
9,nissan,White,31600,4,9700,NaN,19750.000